flags:
  haskeline:
    terminfo: false

allow-different-user: true

build:
  interleaved-output: false

packages:
- yaks/easytest
- parser-typechecker
- unison-core
- unison-cli
- unison-hashing-v2
- unison-share-api
- unison-syntax
- codebase2/codebase
- codebase2/codebase-sqlite
- codebase2/codebase-sqlite-hashing-v2
- codebase2/codebase-sync
- codebase2/core
- codebase2/util
- codebase2/util-serialization
- codebase2/util-term
- lib/unison-prelude
- lib/unison-sqlite
- lib/unison-util-base32hex
- lib/unison-util-base32hex-orphans-aeson
- lib/unison-util-base32hex-orphans-sqlite
- lib/unison-util-bytes
- lib/unison-util-relation
- lib/unison-util-rope
- lib/unison-pretty-printer

resolver: lts-20.0
# Possibly short-term override: downgrade from 9.2.5 to 9.2.4
# This is because as of Nov 29 2022 there is no HLS release compatible with 9.2.5
compiler: ghc-9.2.4
compiler-check: match-exact

extra-deps:
- github: unisonweb/configurator
  commit: e47e9e9fe1f576f8c835183b9def52d73c01327a
- github: awkward-squad/ki
  commit: 563e96238dfe392dccf68d93953c8f30fd53bec8
  subdirs:
    - ki
# This custom Haskeline alters ANSI rendering on Windows.
# If changing the haskeline dependency, please ensure color renders properly in a
# Windows terminal.
# https://github.com/judah/haskeline/pull/126
- github: unisonweb/haskeline
  commit: 6df6d5a0711dd1056b6182559281b31ecfc24773

# these packages aren't in lts-20.0 at all
- co-log-core-0.3.1.0
- fuzzyfind-3.0.0
- lock-file-0.7.0.0
- lsp-1.6.0.0
- monad-validate-1.2.0.1
- recover-rtti-0.4.1.0

# these packages are in lts-20.0, but the pinned version is too old
- shellmet-0.0.4.1

# these packages are transitive dependencies whose pinned versions were either too old or too new, per the above
# deviations to the snapshot
- massiv-0.6.1.0 # due to fuzzyfind-3.0.0; PR: https://github.com/runarorama/fuzzyfind/pull/3
- scheduler-1.5.0 # due to massiv-0.6.1.0

ghc-options:
 # All packages
 "$locals": -Wall -Werror -Wno-name-shadowing -Wno-missing-pattern-synonym-signatures -fprint-expanded-synonyms -fwrite-ide-info #-freverse-errors

 # See https://github.com/haskell/haskell-language-server/issues/208
 "$everything": -haddock
