name: Nix development cache

on:
  push:

jobs:
  nix:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      # Run each build to completion, regardless of if any have failed
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - macOS-12
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
    - uses: cachix/cachix-action@v12
      with:
        name: unison
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: build all packages and development shells
      run: nix -L build --no-link --keep-going '.#all'

